---
title: "Plotting"
author: "Amieroh Abrahams"
date: "18 February 2019"
output: html_document
---

```{r}
library(tidyverse)
library(viridis)
library(plyr)
library(zoo)
library(lubridate)
library(maptools)
library(sp)
library(geosphere)
library(marmap)
library(PBSmapping)
library(scales)
library(grid)
library(gridExtra)
library(mapproj)
library(fossil)
```

# Loading in the data

```{r}
load("Data/metaData2.Rdata")
```




```{r}
# Transects
site_transects <- data.frame()
for(i in 1:length(metaData2$site)){
 site <- metaData2[i,]
 site_transect <- shore.normal.transect(site, 2)
 site_transects <- rbind(site_transects, site_transect)
}

# # Manually correct some transects
site_transects$heading[2:4] <- 290
site_transects$heading[5:6] <- 178
# site_transects$heading[13:14] <- 177.9855
save(site_transects, file = "Data/site_transects.RData")
#write.csv(site_transects, file = "data/site_transects.csv", row.names = F)
load("Data/site_transects.RData")

# Pixel points
site_pixels <- data.frame()
for(i in 1:length(metaData2$site)){
  site <- site_transects[i,]
  site_pixel <- transect.pixel.isobath(site, 25000, -200)
  site_pixels <- rbind(site_pixels, site_pixel)
}
save(site_pixels, file = "Data/site_pixels.RData")
# write.csv(site_pixels, file = "data/site_pixels.csv", row.names = F)
load("Data/site_pixels.RData")

# Bounding box
  # Only one is made in order to know how large the the geom_point() squares should be made to match
test <- data.frame(xmin = destPoint(p = site_pixels[1,2:3], b = 270, d = 12500)[1],
                   xmax = destPoint(p = site_pixels[1,2:3], b = 90, d = 12500)[1],
                   ymin = destPoint(p = site_pixels[1,2:3], b = 180, d = 12500)[2],
                   ymax = destPoint(p = site_pixels[1,2:3], b = 0, d = 12500)[2])

#############################################################################
## Create 200m isobath polygon for plotting

# SA coastline
load("Data/south_africa_coast.RData")
names(south_africa_coast)[1] <- "lon"
south_africa_coast$site <- "SA"

# Manually divide up coastline
wc <- south_africa_coast[291:410,]
sc <- south_africa_coast[132:291,]
ec <- south_africa_coast[23:132,]

# Function for calculating bounding boxes
boundingBoxIso <- function(dat, distance = 400000, isobath = -200){
  #df <- data.frame()
  for(i in rev(1:length(dat$lon))){
    distances <- seq(from = 0, to = distance, by = 1000)
    heading <- shore.normal.transect(dat[i,])
    coords <- data.frame(lon = heading$lon, lat = heading$lat)
    distances2 <- as.data.frame(destPoint(p = coords, b = heading$heading, d = distances))
    sitesIdx <- knnx.index(sa_bathy[,1:2], as.matrix(distances2), k = 1)
    bathy2 <- sa_bathy[sitesIdx,]
    bathy2 <- bathy2[complete.cases(bathy2[,3]),]
    bathy2 <- bathy2[bathy2$depth >= isobath,]
    bathy2 <- bathy2[length(bathy2$depth),]
    if(nrow(bathy2) < 1){
      dat2 <- data.frame(dat[i, ])
    }else{
      dat2 <- cbind(bathy2[,1:2], dat[i,3:8])
    }
    dat <- rbind(dat, dat2)
  }
  return(dat)
}

wcBox <- boundingBoxIso(wc)
wcBox <- wcBox[-c(140:143),] # Remove island
scBox <- boundingBoxIso(sc)
ecBox <- boundingBoxIso(ec)


# isobath200 <- sa_bathy[sa_bathy$depth >= -200,]
# isobath200$coast <- NA
# isobath200$coast[1:1500] <- "west"
# isobath200$coast[1501:3200] <- "south"
# isobath200$coast[3201:4448] <- "east"

#############################################################################
## Create figure showing all the stuffs

# Define plotting parameters
sa_lats <- c(-37, -27); sa_lons <- c(14, 34)

# Plotting with pixel boxes
fig1 <- ggplot() +#coord_equal() + 
  geom_raster(data = sa_bathy, aes(x = lon, y = lat, fill = depth)) +
  #geom_raster(data = isobath200, aes(x = lon, y = lat, fill = coast)) +
  stat_contour(data = sa_bathy, aes(x = lon, y = lat, z = depth, alpha = ..level..), 
               colour = "black", size = 0.2, binwidth = 200, na.rm = TRUE, show_guide = FALSE) +
  geom_polygon(data = south_africa_coast, aes(x = lon, y = lat, group = group), 
               size = 0.5, colour = "black", fill = "white") +
  #geom_path(data = sa_provinces_new, aes(x = long, y = lat, group = group)) +
  geom_polygon(data = wcBox, aes(x = lon, y = lat, group = group), alpha = 0.20, 
               colour = "bisque1", fill = "bisque1") +
  geom_point(data = metaData2, aes(x = lon, y = lat), alpha = 0.8, size = 1.6) +
  geom_point(data = site_pixels, aes(x = lon, y = lat), colour = "white", shape = 0, alpha = 0.8, size = 2.1) +
  geom_rect(data = test, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), 
            alpha = 0.4, colour = "red", size = 0.1, linetype = 1) +
  scale_alpha_continuous(breaks = c(-200, -1000, -2000, -3000, -4000, -5000),
                         guide_legend(title = "depth (m)")) +
  scale_fill_gradient(low = "dodgerblue4", high = "dodgerblue", na.value = "steelblue4", 
                      breaks = c(-1000, -2000, -3000, -4000, -5000),
                      guide_legend(title = "depth (m)")) +
  labs(title = NULL, x = NULL, y = NULL) +
  guides(colour = guide_legend(override.aes = list(size = 3))) +
  #guide_legend(ncol = 2) +
  theme(legend.key = element_rect(colour = NA, size = 0.2),
        legend.key.height = unit(0.4, "cm"),
        legend.background = element_blank()) +
        #legend.justification = c(1,0), legend.position = c(0.5, 0.4)) +
  coord_cartesian(xlim = sa_lons, ylim = sa_lats)
```

