---
title: "Introduction_outline"
author: "Amieroh Abrahams"
date: "13 January 2019"
output:
  pdf_document: default
  html_document: default
---

Chapter 1: General Introduction

## Eastern boundary upwelling systems:

Globally, there are four major eastern boundary upwelling systems (EBUS). These are the Benguela Current off south-western Africa, the Canary Current off north-western Africa including its northern extension off the Iberian Peninsula of south-western Europe, the Peru-Humboldt Current off western South America, and the California Current off the western continental USA and north-western Mexico [@bakun ; @pauly]. Each of these systems are characterized as vast regions of coastal ocean occurring along the western shores of continents bordering the Pacific and Atlantic Oceans. EBUS cover only 1% of the world’s ocean surface, but despite these are among the most productive regions of the world [@pauly]. This is because these systems are subject to coastal upwelling, which is defined as the process whereby cold, nutrient rich, high CO2 concentrated, low pH, and low oxygen waters are pushed to the surface as a result of alongshore winds interacting with the earth’s rotation [@huyer]. As a result of upwelling, diverse marine fauna and flora are able to thrive in these areas because of the abundance of nutrients and favourable temperatures. 

Upwelling is primarily caused by alongshore, equator ward winds. These winds are caused by cross-shore atmospheric pressure gradients, and these gradients occur predominantly during heating periods. Bakun then proposed that if there is an increase in greenhouse gases, it will cause more heating during the day and more cooling during the night which cause the temperature gradient to increase and would result in a strong pressure gradient, and as we know the pressure gradient will affect the wind and therefore will affect upwelling. Several people have tried to model this using different datasets of SST and wind pattern data at various resolution and initially found that increases in gases, such as CO^2 causes a reduction in trade winds, and therefore a reduction in upwelling. However, these models were based on coarse data and when higher resolutions are used, such as for the Benguela EBUS, the models have shown that upwelling will intensify in accordance to the upwelling intensification hypotheses [@hsieh; @mote; @lima].

### Ecology and primary production within upwelling zones:

The duration and intensity of coastal upwelling are known to have a critical role in the phenology of key marine ecosystem processes. Similarly, changes in the characteristics of upwelling are shown to have cause large disturbances to ecosystems at several trophic levels [@wang]. Cold, nutrient rich, low pH, and low oxygen upwelled waters fuels primary production as a consequence of the development of phytoplankton blooms [@ryther; @Cushing; @mcGillicuddy; @oschlies]. In these upwelling systems, the high productivity supports vast and diverse marine populations. Mesoscale and sub-mesoscale oceanic movements are key in managing the exchange and transportation of organic resources and marine organisms from the coastal zone to the open ocean. Most of the world’s major fishing industries are dependent on upwelling, because this process brings nutrient rich waters into the euphotic zone, where it forms the foundation of a localized food web that ecologically differs from surrounding, non-upwelled regions [@bosman; @barshis]. Whilst nutrients play a primary role in the survival of these systems, the cool temperatures of these waters are critical as well. There is an increasingly large body of research that has provided evidence showing that sea surface temperatures (SST) have and are continuing to increase. However, some regions still show a lower or non-significant increase, and in some cases cooling trends are evident (REFERENCES). Upwelling occurring along the Cape south coast is proven to have less of an economic importance in contrast to the west coast. Inshore regions and embayments that are protected from wind action may be subjected to intense episodes of primary production [@graham]. Vander Wouder et al. (2006) found that these sites represent the highest levels of chlorophyll concentration. Biotic systems within the Benguela upwelling system may be negatively influenced by the changes in oxygen levels given their adaption to natural variable conditions [@capone].

For several decades, regime shifts have become an important factor of marine research. Regime shifts are often defined as a shift from one stable ecosystem state to another. This process affects several species within a short period of time [@cury; @jarre; @blamey). Regime shifts are thought to be driven by abiotic processes such as climate change [@polovina; @blamey]. The southern Benguela upwelling system supports a wide variety of commercially-exploited fish species and exhibits substantial variability in both oceanographic and biological components. Over the past 3 three decades, a number of species occurring within this region have undergone shifts in their distributions and Roy et al. (2007) linked these shifts to cooling waters along the inner shelf of the Agulhas bank on the south coast, east of Cape Agulhas [@blamey]. This coast is associated with high levels of harmful toxic algal blooms, which negatively impact commercial and recreational interests along the coastal region. These harmful blooms are often attributed to flagellated species with the red tide representing dinoflagellate blooms (Pitcher et al. 1993A, @pitcher1998]. Formations of red tides are often related to the prevailing winds of the southern Benguela which govern most hydrodynamic processes on the continental shelf. Red tide events are greatest during the latter part of the upwelling season during transitions in the synoptic weather patterns which result in diminished upwelling activity and increased thermal stratification (Pitcher et al. 1993a).

### Atmosphere:

Throughout region surrounding the Benguela EBUS, the atmosphere is dominated by anticyclonic high pressure cells with quasi-stationary positions. The South Atlantic Ocean High is situated along the west, drawing cool, dry air onto the west of the subcontinent [@van]. Solar heating during summer may result in the development of low pressure cells, known as heat lows. These cells are absent during winter time [@tyson]. When the anticyclones shift north, during winter months, the cold westerlies have a substantial impact on the weather of the southern tip of the South African subcontinent [@van]. The atmospheric temperatures along the coastline are largely influenced by the Benguela Current [@van]. However, upwelling systems may be forced by various atmospheric conditions [@Lutjeharms; @roberts; @hutchings].

### Sea surface temperature and data collection:

Water temperature affects the survival, abundance, distribution and growth of marine species (REFERENCE). As such, a clear understanding of the relationship between marine ecosystems and their thermal tolerance is necessary for conservation and management planning. Future predictions in biogeographical patterns and ecosystem functioning may also be estimated based on various climatic behaviours. Regardless of the objectives, whether it be studies based on climate change, extreme events or ecosystem functioning, it is important that the research is conducted through accurate, reliable datasets. Unfortunately, not all data are created equally and under the same conditions and as such not all datasets are usable for a particular task. 

Remotely-sensed satellite SST products are produced and maintained by a number of organisations worldwide. In order to obtain these SST data, advanced technology is launched into space, in order to obtain infra-red light being emitted by the ocean. This irradiance is then taken as a proxy for SST.  Due to the distance at which these SST are being collected, certain coarseness within the datasets are unavoidable. Satellite SST products undergo a range of quality control processes that are well researched and tested [@reynolds], making their use more reliable. However, Smit et al. (2013) have shown that SST data are not particularly reliable for coastal regions and should be used cautiously as they can be prone to both warm and cold bias. Nevertheless, satellite data products are extremely useful when investigating the ocean at broad scale and can provide important SST data.  <will add more here on the different types of resolution used in this thesis>

### In situ data

Having coastal, in situ seawater temperature data is a rare privilege to researchers. Most biological and ecological research requires coastal temperature data. The South African Coastal Temperature Network (SACTN). The availability of the in situ collected coastal temperature data products for several decades and provides a reliable source of accurate coastal seawater temperature data [@smit]. SACTN has collected coastal seawater temperature along the South African coastline from as early as 1972, with contributions from a total of seven different organisations and governmental departments. At present, this dataset contained temperature of 129 sites along the three distinct coasts of the South African coastline. Temperature recordings are still ongoing at many of these sites, but unfortunately, the durations and extents of these are uneve per site. With the longest time series in the dataset being that of Gordons Bay, recorded by SAWS. Data collected for this region started on 13 September 1972 and concluded on 26 January 2017, with recordings still continuing daily. During the 1970s, a total of 11 time series began recording. A further 53 entries were added during the 1980s, 34 entries were added during the 1990s, and 18 entries were added during the 2000s.

The uneven and inconsistent nature of the SATCN dataset can be attributed to several factors. For instance, these may be as a result of variances in the equipment used by the various organisations and governmental bodies who recorded the data. One problematic outcome of this sampling methodology is that due to specific work of the South African Weather Service (SAWS) and Kwazulu Natal Sharks Board (KZNSB), two thirds of the SACTN data that were sampled were obtained with hand-held thermometers and records at a data precision of 0.500 ◦ C. However, the current global standard is to make use of underwater temperature recorders (UTRs), which have a data precision of 0.001◦ C [@jarraud]. Because of these inconsistencies, this dataset required verification from an independent source before its use within research. Smit et al. (2013) thoroughly compared the temperature data within the SACTN dataset to those of several remotely-sensed SST products and found bias results. Using these in situ collected temperature data along with remotely sensed SST data requires a clear understanding in the characteristics of the contributing data sources in order to understand how accurate, reliable and useful these long term measurements are for use in climate change studies.

It must also be acknowledged that most of the time series within the SACTN dataset do not have meta-data records that meet the international climate change research requirements [@aguilar]. Specifically uncertainty lies in the drift of the instrument, who was sampling and where the exact sampling locations were collected throughout the collection period. We are however certain that all of the thermometer time series were collected by thermometers and that the UTR time series were collected by UTRs. Given these issues associated with the mete-data, recent work has been started to develop a nation wide standard.

For this analysis, the seawater temperature data, obtained from the seven different sources, were combined and formatted into standardized comma delineated value (CSV) files which allowed for a fixed methodology to be used across the entire dataset. Prior to data analysis, all data points exceeding 35°C and/or below 0°C were removed as these were considered as outliers. These data points were then changed to NA (not available) so as to not interfere with analysis. All analyses were conducted in R software version 3.4.2 (http://www.r-project.org/). The data used within this study and comprehensive script used for data analyses, and production of figures can be found at https://github.com/AmierohAbrahams/MASTERSPROJECT.

### Climate change:

Climate change as a result of anthropogenic activities is  an established global concern of both scientific and political importance. As the human population grows, the rate of global warming increases, resulting in profound effects on marine and other ecosystems. Climbing temperatures create a host of additional changes to marine systems, such as rising sea levels, increased ocean stratification, decreased sea-ice extent, and altered patterns of ocean circulation and precipitation [@doney]. Furthermore, direct effects on ocean temperature changes and chemistry may alter the functioning and behaviour or marine organisms. In turn, these changes lead to a change in species integration and trophic pathways.

Significant research studies accept the climate change and variability have great impacts on marine ecosystems [@stenseth; @harley; @hoegh]. The Intergovernmental Panel on Climate Change (IPCC) predicts future projections with a mean increase in air temperature of 1.1°C by the 2020’s and 1.8°C by the 2040’s as a result of greenhouse gas concentrations [@solomon]. A large amount of this heat will be absorbed by the world’s ocean. In current years, as a result of changes in air temperature, the heat content of the ocean has increased largely. Given ocean warming in association with their physical changes such as sea level rise and declines in sea ice, marine life is expected to intensify in future decades. Global warming represents distinct warming and cooling periods throughout the 20th and 21st century (IPCC, 2007). Global warming however is not evenly distributed across the global ocean, and thus several regions are warming faster or slower than then García-Reyes et al., 2015 the global average [@levitus; @santos]. In particular, the Atlantic Ocean contributes most to the increase of the heat content [@nerem; @levitus].

As a result of climate change, research studies provide significant evidence relating to the increase in the warming of the ocean surface. This warming slowly propagates down through the water column and in turn increases the thermal stratification [@gruber]. Strong stratification limits the depth at which water is upwelled and hence controls the amount of nutrients brought up [@chhak; @jacox2011; @jocox2016]. The interplay between upwelling winds and stratification determines the amount of nutrients present within the system and is therfore strongly linked to biological productivity. Globally, as a result of climate change, stratification of the water-column between 0 and 200 m has increased by an estimated 4% between 1971 to 2010 [@Stocker]. Increased ocean stratification as a result of surface warming may reduce the ventilation of deep-water masses. As the deep water is being up welled to the surface, decreases in oxygen and pH levels are predicted along with an increase in nutrient levels [@Rykaczewski).  Generally, regional ocean climate oscillations like the Benguela Niño for the Benguela Current System impose considerable variability on temperatures and complicate attempts to assess long-term trends [@demarcq]. It is predicted that these climate oscillations may increase the variance with climate change [@timmermann; @kuzmina; @sydeman] which will further result in unusual trends.

As previously mentioned, upwelling winds in EBUSs are generated by pressure differences between continental thermal lows and oceanic highs. As warming intensifies, pressure gradients between land and sea increases, resulting in a greater intensity of upwelling winds [@bakun2010]. In rare cases, projected upwelling increases may overcome the countervailing effects of upper-ocean warming and stratification to cause regional cooling [@auad]. Research studies reveal declines in ocean oxygen levels as a result of ocean warming and reduced ventilation from stratification and circulation changes [@Keeling]. Similarly, low oxygen levels are also possible because of shifts in the composition of sinking organic material [@hofmann; @doney].

Climate change has severe ecological consequences on both plants and animals (Bradley et al. 1999; Walther et al. 2002). For example, in the past two decades, sea surface temperature has risen in many regions. Seasonal rise in temperature can act as an important cue in species survival, reproduction and abundance (Cushing 1982; Cushing 1990). The differing responses of species as a result of climate change are important to understand as these changes affect, among many things, the trophic dynamics and fisheries yield of several regional ecosystems (Murawski 1993).

Understanding the relationship between global warming and climate change as a result of anthropogenic activity is a vast and challenging process. In a bid to further this understanding, Rockström et al. (2009) introduced the concept of planetary boundaries. According to this concept, within each of these boundaries exists a level of safety that should not be exceeded. For example, the planetary boundary for biodiversity loss, has been surpassed [@steffen]. Similarly, the safety boundary for warming of the globe by greenhouse gas emission has also been surpassed. The idea of planetary boundaries is essential in that it helps our understanding of the threats we cause via the continued destruction of the natural environment. Consequently, studies of anthropogenic influences on the ecosystem are generally divided into land or sea. Terrestrial ecosystems are more familiar to the general populace; whereas marine ecosystems are associated with high levels of primary production [@Chavez] and are highly at risk as a result of climate change [@osterblom]. This has been proven to decrease primary production thus affecting the trophic levels and leading to trophic turbulence and destruction of marine fauna [@lewandowska; @dell, @mcCauley].

Climate change similarly affects coastal species such as oysters, corals and, sea grass. Lord (2017) also found evidence that suggests that a change in climate as a result of rising sea temperatures may increase the spread of invasive species and increase the chances of an outbreak of diseases [@altizer]. Research by Mead et al (2013) found that coastal ecosystems are at high risk as a result of climate change, later, Whitfield et al (2016) confirmed that coastal bio-diversity have been observed to be affected. Given the importance of primary productivity, it was determined that the Benguela upwelling systerm within the South African region should become the focus of this thesis. Here the increase in global temperatures are one of the main focus points along with the chlorophyll concentration. By making use of these two measurements, I am able to analyses how chlorophyll concentration vary with a change in temperature.

## Problem statement:

With global warming continuing at a rapid pace, the amount of greenhouse gases within the atmosphere are going to increase in the future. This increase will undoubtedly have an impact on the world’s oceans and the marine life within, both directly and indirectly. The oceanic process of coastal upwelling is one aspect that is likely to be affected as changes in global temperature will affect temperature and pressure gradients, and in turn affect alongshore winds which are responsible for driving this process within EBUS regions. Because upwelling is important for productivity within coastal systems, a decrease in this process will negatively impact on marine fauna and flora, and on human activities such as fishing. To assess changes in upwelling events, here I aim to use SST, wind, and chlorophyll data to monitor the durations and intensities of upwelling events within the Benguela EBUS and identify wether this resulted in an extreme anomalous cold event. Atmospheric-ocean coupling is known to be affected by climate change, likely changing wind patterns and leading to upwelling favourable conditions (García-Reyes et al., 2015). Here we test if an increase in upwelling may lead to a detection of more MCSs simply because these cold temperatures caused by aseasonal upwelling will reflect in historic climatologies.

## Benguela :

This study focusses on the Benguela EBUS. The Benguela EBUS is unique in that it is bounded at both the equator ward and pole ward ends by warm water regimes. These currents are forced locally by the wind stress field off South-West Africa [@nelson ; @fennel]. This upwelling system stretches along the south-western coast of Africa from southern Angola to Cape Agulhas [@cole, 1999). Water is coldest and most persistent off the Namibian coast at 25°S and weakest at 17°S [@Lutjeharms]. The main upwelling period in the Benguela north of 25°S extends mainly from March to November, peaking during August [@shannon1985], but upwelling persists throughout the year. Upwelling season in the northern Benguela extends between September and March, with very little upwelling taking place during winter (June-August). In the central Benguela and also at Cape Frio upwelling is continuous throughout the year [@shannon1985]. The cold Benguela waters are bound in the south by the warm Agulus retroflexion region and in the north by the southward flowing Angola current. The flow of the Benguela is often considered to be topographically guided [@nelson; @barange; @barange. The Benguela system is split into northern and southern systems by a zone of intense perennial upwelling activity in the Luderitz region within the Namibian region [@shannon; Cole 1999).

Upwelling in the northern Benguela is in phase with the seasonal insulation cycle, whereas in the southern Benguela it is not. The result is that there is a pronounced seasonal cycle in SST in the north while in the south there is no clear SST cycle.  The seasonal warming occurring during the late summer season off northern and central Namibia is a regular occurrence and is associated with warmer, higher salinity water of Angolan origin into the region [@o; @shannon]. There have been a number of warm and cool periods documented in the northern and southern Benguela [e.g. @stander; @walker; @shannon1984; @boyd; @brainard]. Walter (1937) found a major climatic event in the northern Benguela region of anonymously warm water. This unusual warm water may have resulted due to reduced upwelling or an increase southward advection of warm water. Another warming event occurred during the summer and autumn months of 1984 [@shannon1986]. The presence of this anomalous warm water during 1984 followed two cooler than normal years in the northern Benguela. Shannon et al. (1986) illustrated the warm (21-23°C) water near Walvis Bay as a large warm water patch offshore west of Luderitz. The absence of upwelling between Walvis Bay and north of Luderitz is evident however, the upwelling centre in the Benguela system [@shannon1986], and upwelling was minimal. Interestingly, in the southern Benguela region, there was no evidence of any unusual patterns in temperature distributions. The seasonal temperature pattern within the northern Benguela is somewhat similar to that in the eastern equatorial Atlantic and the regular southward intrusion of warm water into the northern Benguela during the summer season. During these warming periods the equator ward wind stress over the northern Benguela region was stronger than normal; yet upwelling was suppressed by the southward movement of warm saline waters from the Angolan region.

Northward, the Benguela Current Upwelling system is linked by the Angola Benguela Front which converge between the Benguela current and the Benguela coastal current as well as the warm saline waters of the Angola Current [@peterson]. Research done by Yamagata and Iizuka (1995) discovered slight indication that coastal Kelvin waves, originating from equatorial Kelvin waves, carry the down welling process southward.  Southward, the coastal upwelling system is bounded by the Agulhas Bank. South of the African coast the warm Agulhas Current, western boundary current, flows in from the Indian Ocean and returns eastwards while generating warm eddies that spin off in a north-westerly direction in the Benguela current [@duncombe]. The region surrounding the Benguela experiences a persistent along shore wind. This wind is associated with the St. Helena high pressure system. Lutjeharms and Meeuwis, (1987) also found a strong relationship between the intensity of upwelling events and the strength and direction of prevailing winds. These favourable upwelling equatorial winds represent a maximum at 25°S and decrease towards the northern and southern boundaries of the Benguela upwelling system. Continental shelf bathymetry and upwelling favourable winds provide a large-scale upwelling mechanism in the southern Benguela, whereas local topography and meteorology create an alternating pattern of active and passive upwelling circulations along the coast. Winds occurring within the southern regions represent a seasonal variation, reaching a maximum during spring and summer months [@boyd; @shannon1996; @fennel]. Winds occurring within this region tend to show increasing patterns away from the coast whereas, winds occurring in the northern region exhibits relatively less seasonal variation [@shannon1985; @pitcher). Upwelling occurring along the South Coast of the Cape Province within South Africa, specifically along the coastline is generated by local wind.  The wind increases somewhat away from the coast. This facilitated the idea of wind stress curl, as discussed in Bakun and Nelson (1991) and Shannon and Nelson (1996).

Benguela Niños are defined as anomalous warm events occurring between the southward flowing Angola current and the Benguela upwelling system off south western Africa [@shannon1986]. These warm events profoundly impact on fisheries and the climate of this region. They are proven to induce unexpected rainfall events and drastically influence fish abundance and distribution [@rouault; @boyer]. Evidently, Benguela Niños are expressed as regions of abnormal, persistent high sea surface temperatures. Many researchers often associate the equatorial interannual variability pattern in the Atlantic to the ENSO phenomenon found within the Pacific region (Sutton et al. 2000; Zebiak 1993). Benguela Niños have been recorded to occur in 1934, 1949, 1963, 1984 and 1995 [@shannon; @gammelsrod]. Picaut (1985) suggested that eastern tropic oceans are governed by remote wind stress effects through equatorial wave dynamics. Anomalies in trade winds may result in Kelvin waves that propagate eastward along the equator, inducing a deepening or a lifting of the thermocline. It is possible that equatorial Kelvin waves may play a role in the evolution of Benguela Niños.

### Extreme events

Extreme thermal events have a range of broad scale definitions, but they can each be classified into two categories, namely, cold-spells [e.g. @gunter; @lirman; @boucek] or heatwaves [e.g. @gordon; @stott; @perkins]. These events occur rapidly, and unexpectedly and they profoundly impact on species diversity, distributions, growth and survival where they take place. These events are often undetected, but studies have found that extreme events have occurred as recently as approximately four decades ago. Jentsch et al. (2007) were the first to discuss this mode of climate change and brought it to greater focus. Steps have since been taken towards understanding the drivers, impacts and consequences of these events. Subsequently, research has predicted an increase in the occurrence of these extreme events as a result of long-term warming of the planet via the process of global warming [@mccabe; @harley; @schoepf].  

Little is known about extreme events occurring within the South African region. Few South African researchers have specifically focussed on investigating this topic, and published literature are sparse. During the 1980’s however, Birkett and Cook analysed the impacts of extreme warming events on the life cycle of white muscles, Donax serra Röding. Futher studies on extreme events occurred within the Florida Reef Tract, where anomolously cold events resulted in the mass mortality of coral reefs and fish. Acropora cervicornis, was found to be particularly susceptible to low temperatures and experienced extensive mortality (Shinn 1966; Davis 1982). While these phenomenons are not as common as warming events, they have a dramtic and long-lasting effect on coral communities. However, studies in January 2010 reveal that the Florida Reef Tract experienced a cold-water anomaly, marine cold spells (MCSs) with temperatures below 16 ◦ C recorded for up to 14 days (Lirman et al. 2011).  Species population distributon are often set by cold distribution boundaries.  More recently, Schlegel et al, (2017, 2018) examined the relationship between the nearshore and offshore occurrences of marine heatwaves and cold-spells as well as the influence of predominant atmospheric and oceanic patterns during Coastal Marine Heatwaves. It is now becoming accepted that extreme events are a threat to several ecosystems [@thompson]. In a warming planet one would assume that the occurrence and intensity of the severity of marine cold spells (MCSs) are likely to decrease. This thesis aims to address this assumption.

## Aims and approach:

The warming of the global climate as a result of anthropogenic activity, has negatively influenced both terrestrial and marine ecosystems, and ultimately inhibits humanity and ecological functioning (McCauley et al., 2015). This climate variability, manifested as increases in frequency and duration of extreme events is regarded as a great threat (Thompsonet al., 2013). Very few studies have addressed the occurrence of cold temperature spells or cold events within the Benguela region. This investigation examines recent trends and variation in the frequency and duration of cold spells occurring in this region. Due to the lack of in situ collected data, cold spells are mainly examined between the period 2014-2017 for four sites along the South African coastline falling within the Benguela upwelling cell. Here we aim to assess whether the intensity and duration of these extreme events may show any changes in frequency and intensity on a seasonal basis. In this research project I make use of various satellite derived observations of sea surface temperature (SST) and wind stress to further investigate the Benguela upwelling system along the South African coastline, whilst considering cold events and warm events occurring within this region

Picaut, J., 1985: Major dynamics affecting the eastern tropical At-
lantic and Pacific Oceans. CalCOFI Report, Vol 26.